spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/match_sim?authSource=admin
      database: match_sim
      authentication-database: admin
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8081