spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      authentication-database: ${MONGO_AUTH}
  mongodb:
    host: mongodb
    port: 27017
    username: ${MONGO_INITDB_ROOT_USERNAME}
    password: ${MONGO_INITDB_ROOT_PASSWORD}

server:
  port: 8081