version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-auth-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: auth
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql-data-auth:/var/lib/mysql
    security_opt:
      - seccomp=unconfined
volumes:
  mysql-data-auth:
    driver: local